USE [Teste]
GO

CREATE TABLE [dbo].[Descontos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Regiao] [varchar](50) NULL,
	[EstadoOrigem] [varchar](50) NULL,
	[Valor] [decimal](18,5) NULL,
 CONSTRAINT [PK_Descontos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO