USE Teste
ALTER TABLE NotaFiscalItem ADD BaseIpi DECIMAL(18,5) NULL
ALTER TABLE NotaFiscalItem ADD AliquotaIpi DECIMAL(18,5) NULL
ALTER TABLE NotaFiscalItem ADD ValoIpi DECIMAL(18,5) NULL
ALTER TABLE NotaFiscalItem ADD Desconto DECIMAL(18,5) NULL