USE [Teste]
GO
IF OBJECT_ID('dbo.P_REPORT_CFOP') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_REPORT_CFOP
    IF OBJECT_ID('dbo.P_REPORT_CFOP') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_REPORT_CFOP >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_REPORT_CFOP APAGADA >>>'
END
go
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE dbo.P_REPORT_CFOP 
AS
BEGIN
	SELECT Cfop, 
		   SUM(BaseIcms) AS ValorTotalBaseICMS, 
		   SUM(ValorIcms) AS ValorTotalICMS , 
		   SUM(BaseIpi) AS ValorTotalBaseIPI, 
		   SUM(ValorIpi) AS ValorTotalIPI
		FROM NotaFiscalItem
	GROUP BY Cfop
END
GO
GRANT EXECUTE ON dbo.P_REPORT_CFOP TO [public]
go
IF OBJECT_ID('dbo.P_REPORT_CFOP') IS NOT NULL
    PRINT '<<< PROCEDURE dbo.P_REPORT_CFOP P_REPORT_CFOP >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_REPORT_CFOP >>>'
go


